### ISSUE TITLE
Unable to pair gamepad. Bluetooth setups says to type a long # into gamepad

### ISSUE THREAD

**Issue by michael-conrad** [mate-desktop-legacy-archive/mate-bluetooth#14]
Unable to pair gamepad. Bluetooth setups says to type a long # into gamepad ?????

I am trying to pair up a gamepad (OUYA controller):

I set the gamepad to discoverable.
I search for new devices.
I select "Ouya Game Controller", Type: "Joypad"
I select PIN options and choose '0000'
I click forward, I then get prompted with "Please enter the following PIN on 'OUYA Game Controller'" ????????

**Comment by stefano-k** [comment]
In 1.8 we'll drop mate-bluetooth for blueman (https://github.com/blueman-project/blueman)
