### ISSUE TITLE
Dependency issue with arch package

### ISSUE THREAD

**Issue by CarbonFixer** [mate-desktop-legacy-archive/mate-bluetooth#15]
gvfs-obexftp has now been merged into a single gvfs package in arch, so should be removed as a dependency in the MATE repository for arch.

$ sudo pacman -Syu
:: Synchronizing package databases...
 xorg112 is up to date
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 mate is up to date
:: Starting full system upgrade...
:: Replace gvfs-obexftp with extra/gvfs? [Y/n] y
resolving dependencies...
looking for inter-conflicts...
error: failed to prepare transaction (could not satisfy dependencies)
:: mate-bluetooth: requires gvfs-obexftp

**Comment by stefano-k** [comment]
This is for upstream issues.
Use https://github.com/mate-desktop/archlinux-packages/issues/new instead.
Thank you.
Closing.
