### ISSUE TITLE
gvfs-obexftp is no longer available for Bluez5

### ISSUE THREAD

**Issue by tarakbumba** [mate-desktop-legacy-archive/mate-bluetooth#17]
I maintain Mate packages for Mageia 4 (Upcoming dev release). Mate-bluetooth depends on obexftp but upcoming Bluez 5 is no longer include it and api changed to use dbus. Mate-bluetooth also should migrate to this new bluez5 version.Also It should be fixed for mate 1.6 series. Thanks.

See:

http://mm3test.fedoraproject.org/hyperkitty/list/devel@mm3test.fedoraproject.org/thread/VLGAL3BCJAPMQWINBVZXYJ6AGK3ERABJ/

https://bbs.archlinux.org/viewtopic.php?pid=1334540

http://fedoraproject.org/wiki/Changes/Bluez5

https://mail.gnome.org/archives/desktop-devel-list/2013-August/msg00121.html

**Comment by stefano-k** [comment]
In 1.8 we'll drop mate-bluetooth for blueman (https://github.com/blueman-project/blueman)
