### ISSUE TITLE
Failed to build on Gentoo (with dbus 1.8.0)

### ISSUE THREAD

**Issue by rene** [mate-desktop-legacy-archive/mate-bluetooth#22]
Make output:
make[2]: Entering directory '/tmp/mate-bluetooth/lib'
  GEN      marshal.h
  GEN      marshal.c
  GEN      bluetooth-client-glue.h
Unable to load "bluetooth-client.xml": "manager" is not a valid D-Bus interface name
Makefile:1101: recipe for target 'bluetooth-client-glue.h' failed
make[2]: **\* [bluetooth-client-glue.h] Error 1
make[2]: Leaving directory '/tmp/mate-bluetooth/lib'

My system:
Gentoo, kernel 3.14.0
dbus - 1.8.0
Bluez - 5.17
Glib - 2.38.2
obexd - 0.46
libunique - 3.0.2

**Comment by raveit65** [comment]
mate-bluetooth doesn't support bluez-5 and it is obsolete.
Mate has switched to https://github.com/blueman-project/blueman
which support bluez5

marked as can be closed, imo

**Comment by infirit** [comment]
Someone posted a patch which you can find here (untested and unsupported) https://github.com/infirit/mate-bluetooth/commits/bluez5

**Comment by Zenitur** [comment]
Patch: https://github.com/openembedded/meta-openembedded/blob/master/meta-gnome/recipes-gnome/gnome-bluetooth/gnome-bluetooth/0002-bluetooth-client-use-valid-interface-names.patch

**Comment by raveit65** [comment]
mate-bluetooth i obsotete an replaced with blueman.
