### ISSUE TITLE
gnome-user-share

### ISSUE THREAD

**Issue by filippoaceto** [mate-desktop-legacy-archive/mate-bluetooth#24]
i have installed gnome-bluetooth in my arch distribution.
To receive file i need to install and launch gnome-user-share. 
With mate-user-share only, archlinux refuse to accept files.
Thanks!

**Comment by stefano-k** [comment]
Issue opened in wrong package
However, we are going to use blueman now, not gnome-bluetooth
http://www.mate-desktop.org/blog/2014-03-04-mate-1-8-released/
http://www.mate-desktop.org/blog/2014-03-11-mate-desktop-singing-the-bluez/
