### ISSUE TITLE
Bluetooth not working on Sparky 4 586

### ISSUE THREAD

**Issue by nabilh2020** [mate-desktop-legacy-archive/mate-bluetooth#26]
Using Hannspree micro-pc, Intel Atom Quadcore, an Intel HDMI stick clone.

None of the bluetooth dongles or integrated worked, when I insert a USB one, the BT icon appears in the title bar, but says disabled when opened, enabling does not make work.

It will be nicer if the integrated BT worked, but even USB don't.

The integrated BT is from Realtek,

Wifi integrated also does not work, but usb dongle from Edimax worked.

Here is a link to the dmesg:

https://www.dropbox.com/s/5fcikyj1kp2fc3j/dmesg.txt.tar.gz?dl=0

**Comment by flexiondotorg** [comment]
mate-bluetooth is discontinued. We recommend using Blueman.
