### ISSUE TITLE
Configuration problem with bluetooth

### ISSUE THREAD

**Issue by Frannoe** [mate-desktop-legacy-archive/mate-bluetooth#3]
There are problems setting up file sharing from the bluetooth.
There is no package  mate-user-share is the one who should manage this.
It is then necessary to use gnome-user-share

The solution for now is to rename the file /usr/bin/gnome-file-share-properties to mate-file-share-properties.

Regards

**Comment by szesch** [comment]
gnome-user-share has now been forked. mate-user-share will be available in our 1.4 release.

**Comment by Frannoe** [comment]
Thanks
