### ISSUE TITLE
Bug with sending files

### ISSUE THREAD

**Issue by CopyKat** [mate-desktop-legacy-archive/mate-bluetooth#5]
After trying to send files via mate-bluetooth-applet,  appeared an error

```
The name.org.openobex.client was not provided any .service files
```

Arch Linux

mate-bluetooth v.1.4.0-1
obexd-client has v.0.47-1 
gvfs-obexftp v.1.12.3-3

**Comment by CopyKat** [comment]
Began working after downgrading bluez to version 4.56-1

**Comment by sbalneav** [comment]
Working.  Closed.
