### ISSUE TITLE
Bug mate-bluetooth wizard

### ISSUE THREAD

**Issue by dpox** [mate-desktop-legacy-archive/mate-bluetooth#9]
Hi all,
when I run this command "mate-bluetooth-properties" and then I press "Set up new device..." I get this error "Couldn't execute command: bluetooth-wizard"

If I do the same thing whit "mate-bluetooth-applet" I have no error.

Looking at the source code, I found this:

/properties/adapter.c

[Line: 148]

static void wizard_callback(GtkWidget *button, gpointer user_data)
{
    const char *command = "bluetooth-wizard";

```
if (!g_spawn_command_line_async(command, NULL))
    g_printerr("Couldn't execute command: %s\n", command);
```

}

and I think that the correct code could be

static void wizard_callback(GtkWidget *button, gpointer user_data)
{
    const char *command = "mate-bluetooth-wizard"; //Adding "mate" 

```
if (!g_spawn_command_line_async(command, NULL))
    g_printerr("Couldn't execute command: %s\n", command);
```

}

I use Linux Mint Nadia 14
mate-bluetooth v 1.2.0-1

**Comment by stefano-k** [comment]
this already fixed in 1.3+
8e98dfc
